import type { CSSProperties } from "react";
import type { ThemeTokens } from "@/types/landing";

export const jordanTheme: ThemeTokens = {
  color: {
    bg: "#000000",
    bgTop: "#05070b",
    foreground: "#f7f9fc",
    foregroundSoft: "rgba(247, 249, 252, 0.72)",
    primary: "#cc0000",
    primarySoft: "rgba(204, 0, 0, 0.14)",
    primaryStrong: "#ff5c5c",
    secondary: "#00bfff",
    surface: "rgba(8, 11, 15, 0.88)",
    surfaceStrong: "rgba(10, 14, 19, 0.96)",
    surfaceAccent: "rgba(0, 191, 255, 0.08)",
    borderSoft: "rgba(255, 255, 255, 0.08)",
    borderStrong: "rgba(204, 0, 0, 0.22)",
    gridLine: "rgba(0, 191, 255, 0.08)",
    glow: "rgba(204, 0, 0, 0.16)",
    success: "#00bfff",
    danger: "#cc0000",
  },
  type: {
    display: "clamp(2.4rem, 5.2vw, 4.85rem)",
    heading: "clamp(1.62rem, 3.7vw, 2.9rem)",
    subheading: "clamp(1.02rem, 1.8vw, 1.32rem)",
    cardTitle: "clamp(1.1rem, 1.85vw, 1.42rem)",
    bodyLg: "clamp(1rem, 1.35vw, 1.14rem)",
    body: "0.98rem",
    label: "0.82rem",
    meta: "0.88rem",
    metric: "clamp(1.45rem, 3vw, 2.5rem)",
    metricSecondary: "1.1rem",
    stat: "0.92rem",
  },
  radius: {
    sm: "0.75rem",
    md: "1rem",
    lg: "1.35rem",
    xl: "2rem",
    pill: "999px",
  },
  space: {
    sectionY: "clamp(3.5rem, 7vw, 5.75rem)",
    sectionYMobile: "2.9rem",
    containerX: "clamp(1rem, 4vw, 2rem)",
    cardPadding: "clamp(1rem, 2vw, 1.35rem)",
    gridGap: "clamp(0.85rem, 1.6vw, 1.15rem)",
  },
  shadow: {
    soft: "0 18px 54px rgba(0,0,0,0.42)",
    card: "0 26px 76px rgba(0,0,0,0.46)",
    hero: "0 38px 120px rgba(0,0,0,0.56)",
    glow: "0 0 42px rgba(204,0,0,0.12)",
  },
  motion: {
    durationFast: 220,
    durationBase: 420,
    durationSlow: 760,
    durationLoop: 5200,
    easingStandard: "easeOutCubic",
    easingEntrance: "cubicBezier(0.22, 1, 0.36, 1)",
    easingEmphasis: "easeOutExpo",
  },
};

export function jordanThemeStyle(): CSSProperties {
  return {
    "--color-bg": jordanTheme.color.bg,
    "--color-bg-top": jordanTheme.color.bgTop,
    "--color-foreground": jordanTheme.color.foreground,
    "--color-foreground-soft": jordanTheme.color.foregroundSoft,
    "--color-primary": jordanTheme.color.primary,
    "--color-primary-soft": jordanTheme.color.primarySoft,
    "--color-primary-strong": jordanTheme.color.primaryStrong,
    "--color-secondary": jordanTheme.color.secondary,
    "--color-surface": jordanTheme.color.surface,
    "--color-surface-strong": jordanTheme.color.surfaceStrong,
    "--color-surface-accent": jordanTheme.color.surfaceAccent,
    "--color-border-soft": jordanTheme.color.borderSoft,
    "--color-border-strong": jordanTheme.color.borderStrong,
    "--color-grid-line": jordanTheme.color.gridLine,
    "--color-glow": jordanTheme.color.glow,
    "--color-success": jordanTheme.color.success,
    "--color-danger": jordanTheme.color.danger,
    "--electric-red": jordanTheme.color.primary,
    "--electric-blue": jordanTheme.color.secondary,
    "--carbon-black": "#05070b",
    "--silver": "#c0c0c0",
    "--glow-intensity": "0.5",
    "--border-accent": `2px solid ${jordanTheme.color.primary}`,
    "--font-modern": '"Helvetica Neue", Arial, sans-serif',
    "--font-display-size": jordanTheme.type.display,
    "--font-heading-size": jordanTheme.type.heading,
    "--font-subheading-size": jordanTheme.type.subheading,
    "--font-card-title-size": jordanTheme.type.cardTitle,
    "--font-body-lg-size": jordanTheme.type.bodyLg,
    "--font-body-size": jordanTheme.type.body,
    "--font-label-size": jordanTheme.type.label,
    "--font-meta-size": jordanTheme.type.meta,
    "--font-metric-size": jordanTheme.type.metric,
    "--font-metric-secondary-size": jordanTheme.type.metricSecondary,
    "--font-stat-size": jordanTheme.type.stat,
    "--radius-sm": jordanTheme.radius.sm,
    "--radius-md": jordanTheme.radius.md,
    "--radius-lg": jordanTheme.radius.lg,
    "--radius-xl": jordanTheme.radius.xl,
    "--radius-pill": jordanTheme.radius.pill,
    "--space-section-y": jordanTheme.space.sectionY,
    "--space-section-y-mobile": jordanTheme.space.sectionYMobile,
    "--space-container-x": jordanTheme.space.containerX,
    "--space-card-padding": jordanTheme.space.cardPadding,
    "--space-grid-gap": jordanTheme.space.gridGap,
    "--shadow-soft": jordanTheme.shadow.soft,
    "--shadow-card": jordanTheme.shadow.card,
    "--shadow-hero": jordanTheme.shadow.hero,
    "--shadow-glow": jordanTheme.shadow.glow,
  } as CSSProperties;
}
